version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: bookstore
    environment:
      POSTGRES_DB: bookstoredb      
      POSTGRES_USER: Ilya          
      POSTGRES_PASSWORD: 200 
    ports:
      - "5432:5432"                
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:             