version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: bookstoreIlys
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: bookstoredb
      MYSQL_USER: Ilya
      MYSQL_PASSWORD: 2004
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: